version: 0.0
os: linux
files:
  - source: /
    destination: /opt/www/prfaa-donations-backend
  - source: /config/extra_keys
    destination: /home/ec2-user/.ssh/
permissions:
  - object: /opt/www/prfaa-donations-backend
    pattern: "**"
    owner: ec2-user
    group: ec2-user
hooks:
  ApplicationStop:
    - location: scripts/stop-app.sh
      runas: ec2-user
  BeforeInstall:
    - location: scripts/install-nodejs.sh
      runas: ec2-user
  AfterInstall:
    - location: scripts/install-keys.sh
  ApplicationStart:
    - location: scripts/start-app.sh
      runas: ec2-user
  ValidateService:
    - location: scripts/monitor-app.sh
      runas: ec2-user
